package fr.ynov.dap.data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * the microsoft account linked to the appUser in database.
 * @author Antoine
 *
 */
@Entity
public class MicrosoftAccount {
  /**
   * generated by JPA.
   */
  @Id
  @GeneratedValue
  private int id;
  /**
   * Many GoogleAccounts are linked to an appUser.
   */
  @ManyToOne
  private AppUser appUser;
  /**
   * the name of the google account.
   */
  private String microsoftAccountName;

  /**
   * get the generated Id.
   * @return an int
   */
  public int getId() {
    return id;
  }

  /**
   * get the user used in Ynov Dap.
   * @return a appUser
   */
  public AppUser getAppUser() {
    return appUser;
  }

  /**
   * set the appUser.
   * @param applicationUser the new appUser
   */
  public void setAppUser(final AppUser applicationUser) {
    this.appUser = applicationUser;
  }

  /**
   * get the microsoft account.
   * @return a string
   */
  public String getMicrosoftAccountName() {
    return microsoftAccountName;
  }

  /**
   * set the microsoft account.
   * @param microAccountName the new account name
   */
  public void setMicrosoftAccountName(final String microAccountName) {
    this.microsoftAccountName = microAccountName;
  }

}
