package fr.ynov.dap.data;

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Antoine
 * a class that knows all google accounts for a specific user.
 */
@Entity
public class AppUser {
  /**
   * the unique identifier in database.
   */
  @Id
  @GeneratedValue
  private int id;
  /**
   * the identifier used by the app.
   */
  private String userKey;
  /**
   * All the googleAccounts linked to the userKey.
   */
  @OneToMany(cascade = CascadeType.ALL, mappedBy = "appUser")
  private List<GoogleAccount> googleAccounts;
  /**
   * get the userKey.
   * @return userKey
   */
  public String getUserKey() {
    return userKey;
  }
  /**
   * set the userKey.
   * @param userId the new userKey
   */
  public void setUserKey(final String userId) {
    this.userKey = userId;
  }
  /**
   * get All google accounts for the identifier userKey.
   * @return the google accounts that has been added
   */
  public List<GoogleAccount> getGoogleAccounts() {
    return googleAccounts;
  }
  /**
   * set the list of GoogleAccounts for the identifier userKey.
   * @param listGoogleAccounts the list that contains all accounts
   */
  public void setGoogleAccounts(final List<GoogleAccount> listGoogleAccounts) {
    this.googleAccounts = listGoogleAccounts;
  }
  /**
   * get the unique identifier generated by Hibernate.
   * @return the unique id
   */
  public int getId() {
    return id;
  }

  /**
   * Add new token in credentialFolder for the user specified.
   * @param account the account for the identifier userKey
   */
  public void addGoogleAccount(final GoogleAccount account) {
    account.setAppUser(this);
    this.getGoogleAccounts().add(account);
  }
}
