package fr.ynov.dap.data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class GoogleAccount {
  @Id
  @GeneratedValue
  private int id;
  @ManyToOne
  private AppUser appUser;
  /**
   * get the unique identifier generated by Hibernate.
   * @return the appUser
   */
  public AppUser getAppUser() {
    return appUser;
  }
  /**
   * set the unique identifier generated by Hibernate.
   * @param applicationUser the appUser
   */
  public void setAppUser(final AppUser applicationUser) {
    this.appUser = applicationUser;
  }
  /**
   * get the id generated value.
   * @return the id
   */
  public int getId() {
    return id;
  }
}
